# Generated by Django 3.0.3 on 2020-03-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_hidden',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_vault_psw',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
